optimizations
CHANGES OVERVIEW
- Rename core functions
- Create structure for maintaining process information
- Optimize class constructor
- Include initialization functions
- include ease of use functions which make use of core methods

BUG FIXES
- WriteVirtualMemory

dump to file

fix: C2440

error: 'initializing' : cannot convert from 'type1' to 'type2'

resolved by removing template type initializer in template read methods